spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  sql:
    init:
      mode: always
server:
  port: 8080
