services:
  transaction-service:
    build: transaction-service
    image: transaction-service
    container_name: transaction-service-container
    ports:
      - "8080:8080"
    depends_on:
      - transaction-db
    environment:
      - DB_HOST=transaction-db
      - DB_NAME=transaction-db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  transaction-db:
    image: postgres:17.0-alpine
    container_name: transaction-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=transaction-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root